#!/usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser(description="replace carriage return with linefeeds")
parser.add_argument("files", nargs="*", type=open)
args = parser.parse_args()
files = args.files

files = [sys.stdin] if not args.files else args.files

for file in files:
    for line in file:
        line = line.replace('\r\n', '\n')
        line = line.replace('\r', '\n', 1000)
        sys.stdout.write(line)
