#! /usr/bin/env bash
# vim:ft=sh
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo '{'
echo "  "\""path"\"":"\""$(pwd)"\"","
echo -n "  "\""contents"\"":"
ls | awk -f ${MY_DIR}/awk/list_to_array_of_names.awk
echo '}'
