#! /usr/bin/env bash 

# make sure that we're only getting input from the command line
unset FILE
unset COMMENT
unset URL
unset TAGS

eval "$(args_to_env "$@")"

export FILE=${FILE?You need to provide a path to a file so we can add it to DTP}
add_to_devon
