#! /usr/bin/env bash
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PYTHONPATH=$PYTHONPATH:${MY_DIR}

function abspath {
    if [[ -d "$1" ]]; then
        pushd "$1" >/dev/null
        pwd
        popd >/dev/null
    elif [[ -e $1 ]]; then
        pushd "$(dirname "$1")" >/dev/null
        echo "$(pwd)/$(basename "$1")"
        popd >/dev/null
    else
        echo "$1" does not exist! >&2
        return 127
    fi
}
export -f abspath

function send_command(){
  if [ ! -w "$(pwd)/.runnerfifo" ]; then
    echo "you must be in an active runner directory"
    exit 1
  fi

  case "${1}" in
    "start")
        echo '{"name":"add_process","path_to_executable":"'$(abspath ${2})'"}' > .runnerfifo
      ;;
    "list")
        echo '{"name":"list_processes"}' > .runnerfifo
      ;;
  esac
  
}

COMMAND=$1
shift
case "${COMMAND}" in
  "start")
    # adds or starts a process
    send_command 'start' "$1"
    ;;
  "stop")
    # stop a process by pid?
    echo stop process
    ;;
  "list")
    send_command 'list'
    ;;
  *)
    # if the arguments is the name of a file in the working directory, then
    # we'll get the list of info about any processes using it
    python -m runner_py
    ;;
esac
