#! /usr/bin/env bash

echo  curl -w "\n%{time_total} :time_total\n%{time_connect} :time_connect\n%{time_appconnect} :time_appconnect\n%{time_redirect} :time_redirect\n%{time_starttransfer} :time_starttransfer\n%{time_namelookup} :time_namelookup\n%{time_pretransfer} :time_pretransfer\n" "$@"
curl -s --head -H "Pragma: no-cache" -H "Cache-Control: no-cache" -w "\n%{time_total} :time_total\n%{time_connect} :time_connect\n%{time_appconnect} :time_appconnect\n%{time_redirect} :time_redirect\n%{time_starttransfer} :time_starttransfer\n%{time_namelookup} :time_namelookup\n%{time_pretransfer} :time_pretransfer\n" "$@"
